apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
spec:
  interval: 1m
  chart:
    spec:
      chart: infra/k8s/chart/hello-world
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    profile: dev
    image:
      repository: 162501354347.dkr.ecr.ap-northeast-2.amazonaws.com/hello-world-dev
      tag: 0.0.1-rc.0
