apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-world
  namespace: flux-system
spec:
  image: 162501354347.dkr.ecr.ap-northeast-2.amazonaws.com/hello-world-dev
  secretRef:
    name: ecr-credentials
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-world
  policy:
    semver:
      range: ">=0.0.0"
