apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../../chart/hello-world
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: hello-world
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
