VERSION 0.7
FROM node:20-alpine
WORKDIR /app

deps:
    RUN corepack enable
    COPY . .
    RUN pnpm install

build:
    FROM +deps
    RUN pnpm run build
    SAVE ARTIFACT out AS LOCAL out

docker:
    FROM +build
    ARG PROFILE
    EXPOSE 80
    ENTRYPOINT ./node_modules/.bin/env-cmd -f .env.${PROFILE} pnpm start
    SAVE IMAGE hello-world:latest
