VERSION 0.7
FROM node:20-alpine
WORKDIR /app

deps:
    RUN corepack enable
    COPY . .
    RUN pnpm install

build:
    FROM +deps
    RUN pnpm run build
    SAVE ARTIFACT out AS LOCAL out

docker:
    ARG version='latest'
    FROM +build
    EXPOSE 80
    ENTRYPOINT pnpm start
    SAVE IMAGE hello-world:${version}
