---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-world
  policy:
    semver:
      range: ">0.0.0-rc"
