name: Build and Push

on:
  workflow_call:
    inputs:
      profile:
        type: string
        required: true
      path:
        type: string
        required: true

jobs:
  app:
    name: Parse app.yaml
    uses: ./.github/workflows/parse-app-yaml.yaml
    with:
      path: ${{ inputs.path }}

  build-and-push:
    name: Build and push
    environment: ${{ inputs.profile }}
    needs: app
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v4
      - id: semver
        uses: madhead/semver-utils@latest
        with:
          version: ${{ needs.app.outputs.version }}
      - name: Get next version
        id: next-version
        run: |
          if [[ "${{ inputs.profile }}" == "dev" ]]; then
            VERSION="${{ steps.semver.outputs.release }}-${{ github.sha }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Build Docker image
        run: earthly ${{ inputs.path }}/+docker --name=${{ needs.app.outputs.name }} --version=${{ steps.next-version.outputs.version }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          NAME: ${{ needs.app.outputs.name }}
          PROFILE: ${{ inputs.profile }}
          IMAGE_TAG: ${{ steps.next-version.outputs.version }}
        run: |
          docker tag $NAME:$IMAGE_TAG $REGISTRY/$NAME-$PROFILE:$IMAGE_TAG
          docker push $REGISTRY/$NAME-$PROFILE:$IMAGE_TAG
