name: Build and Push

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
      profile:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v4
      - id: name
        uses: mikefarah/yq@master
        with:
          cmd: yq '.name' ${{ inputs.path }}/app.yaml
      - name: Build Docker image
        run: earthly ${{ inputs.path }}/+docker --name=${{ steps.name.outputs.result }} --version=${{ inputs.version }}

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: hello-world-${{ inputs.profile }}
          IMAGE_TAG: ${{ inputs.version }}
        run: |
          docker tag hello-world:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
