name: Hello World Release

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  workflow_dispatch:
    inputs:
      profile:
        description: 'Environment profile'
        type: choice
        required: true
        options:
          - dev
        default: dev

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  app:
    name: Parse app.yaml
    needs: check
    uses: ./.github/workflows/parse-app-yaml.yaml
    with:
      path: ./apps/hello-world

  release:
    name: Release
    needs: app
    uses: ./.github/workflows/release.yaml
    with:
      type: ${{ inputs.type }}
      name: ${{ needs.app.outputs.name }}
      version: ${{ needs.app.outputs.version }}
      path: ./apps/hello-world
    secrets: inherit
