name: Hello World Release

on:
  push:
    branches: [ main, release/hello-world-v* ]
    paths:
      - 'apps/hello-world/**'
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of release'
        type: choice
        required: true
        options:
          - pre-patch
          - patch
          - pre-minor
          - minor
          - pre-major
          - major

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  release:
    name: Release
    needs: check
    uses: ./.github/workflows/release.yaml
    with:
      type: ${{ github.event_name == 'workflow_dispatch' && inputs.type || 'pre-release' }}
      path: ./apps/hello-world
    secrets: inherit
