name: Hello World Release

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  workflow_dispatch:
    inputs:
      type:
        description: Release type
        type: choice
        required: true
        options:
          - patch
          - preminor
          - minor
          - major
        default: preminor

jobs:
  app:
    name: Parse app.yaml
    uses: ./.github/workflows/parse-app-yaml.yaml
    with:
      path: ./apps/hello-world

  release:
    name: Release
    needs: app
    uses: ./.github/workflows/release.yaml
    with:
      type: ${{ inputs.type }}
      name: ${{ needs.app.outputs.name }}
      version: ${{ needs.app.outputs.version }}
      path: ./apps/hello-world
    secrets: inherit
