name: Hello World Release

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  workflow_dispatch:
    inputs:
      profile:
        description: 'Environment profile'
        type: choice
        required: true
        options:
          - dev
        default: dev

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  auto-release:
    name: Release
    needs: check
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yaml
    with:
      path: ./apps/hello-world
    secrets: inherit
