name: Hello World CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  workflow_dispatch:

env:
  APP_PATH: ./apps/hello-world

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  next-version:
    name: Get next version
    needs: check
    uses: ./.github/workflows/next-version.yaml
    with:
      path: ${{ env.APP_PATH }}
      profile: dev

  build-and-push:
    name: Build and push
    needs: next-version
    uses: ./.github/workflows/build-and-push.yaml
    with:
      path: ${{ env.APP_PATH }}
      profile: dev
      version: ${{ needs.next-version.outputs.version }}
