name: Hello World Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: Release type ([MAJOR].[MINOR])
        type: choice
        required: true
        options:
          - MINOR
          - MAJOR
        default: MINOR

jobs:
  app:
    name: Parse app.yaml
    uses: ./.github/workflows/parse-app-yaml.yaml
    with:
      path: ./apps/hello-world

  release:
    name: Release
    needs: app
    uses: ./.github/workflows/release.yaml
    with:
      type: ${{ inputs.type }}
      name: ${{ needs.app.outputs.name }}
      version: ${{ needs.app.outputs.version }}
      path: ./apps/hello-world
