name: Hello World CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/hello-world/**'
  workflow_dispatch:

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  build-and-push:
    strategy:
      matrix:
        profile: [ 'dev', 'qa', 'prod' ]
        include:
          - profile: dev
            condition: github.ref == 'refs/heads/main'
    name: Build and push
    needs: check
    runs-on: ubuntu-latest
    steps:
      - if: ${{ matrix.condition }}
        uses: ./.github/workflows/build-and-push.yaml
        with:
          profile: ${{ matrix.profile }}
          path: ./apps/hello-world
