name: Next Version

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
      version:
        type: string
        required: true
    outputs:
      version:
        value: ${{ jobs.next-version.outputs.version }}

jobs:
  next-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.next-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: semver
        uses: madhead/semver-utils@latest
        with:
          version: ${{ inputs.version }}
          identifier: 'rc'
      - name: Get next version
        id: next-version
        run: |
          if [[ "${{ inputs.type }}" == "pre-release" ]]; then
            VERSION="${{ steps.semver.outputs.inc-prerelease }}"
          elif [[ "${{ inputs.type }}" == "pre-patch" ]]; then
            VERSION="${{ steps.semver.outputs.inc-prepatch }}"
          elif [[ "${{ inputs.type }}" == "patch" ]]; then
            VERSION="${{ steps.semver.outputs.inc-patch }}"
          elif [[ "${{ inputs.type }}" == "pre-minor" ]]; then
            VERSION="${{ steps.semver.outputs.inc-preminor }}"
          elif [[ "${{ inputs.type }}" == "minor" ]]; then
            VERSION="${{ steps.semver.outputs.inc-minor }}"
          elif [[ "${{ inputs.type }}" == "pre-major" ]]; then
            VERSION="${{ steps.semver.outputs.inc-premajor }}"
          elif [[ "${{ inputs.type }}" == "major" ]]; then
            VERSION="${{ steps.semver.outputs.inc-major }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash
