name: Get Next Version

on:
  workflow_call:
    inputs:
      profile:
        type: string
        required: true
      type:
        type: string
        required: true
      version:
        type: string
        required: true
    outputs:
      version:
        value: ${{ jobs.next-version.outputs.version }}

jobs:
  next-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.next-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: semver
        uses: madhead/semver-utils@latest
        with:
          version: ${{ inputs.version }}
      - name: Get next version
        id: next-version
        run: |
          if [[ "${{ inputs.profile }}" == "prod" ]]; then
            if [[ "${{ inputs.type }}" == "major" ]]; then
              VERSION="${{ steps.semver.outputs.inc-major }}"
            elif [[ "${{ inputs.type }}" == "minor" ]]; then
              VERSION="${{ steps.semver.outputs.inc-minor }}"
            elif [[ "${{ inputs.type }}" == "patch" ]]; then
              VERSION="${{ steps.semver.outputs.inc-patch }}"
            fi
          elif [[ "${{ inputs.profile }}" == "qa" -o "${{ inputs.profile }}" == "dev" ]]; then
            if [[ "${{ inputs.type }}" == "major" ]]; then
              VERSION="${{ steps.semver.outputs.inc-premajor }}"
            elif [[ "${{ inputs.type }}" == "minor" ]]; then
              VERSION="${{ steps.semver.outputs.inc-preminor }}"
            elif [[ "${{ inputs.type }}" == "patch" ]]; then
              VERSION="${{ steps.semver.outputs.inc-prepatch }}"
            fi
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash
