name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - '!infra/pulumi/**'
  pull_request:
    branches: [ main ]
    paths:
      - '!infra/pulumi/**'
  workflow_dispatch:

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml
