name: Pulumi Release

on:
  push:
    branches: [ main, release/infra-v* ]
    paths:
      - 'infra/pulumi/**'
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of release'
        type: choice
        required: true
        options:
          - pre-patch
          - patch
          - pre-minor
          - minor
          - pre-major
          - major

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  up:
    name: Pulumi Up
    needs: check
    uses: ./.github/workflows/pulumi-up.yaml
    with:
      type: ${{ github.event_name == 'workflow_dispatch' && inputs.type || 'pre-release' }}
    secrets: inherit
