name: Pulumi

on:
  push:
    branches: [ main, release/* ]
    paths:
      - 'infra/pulumi/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/pulumi/**'
  workflow_dispatch:

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  preview:
    strategy:
      matrix:
        profile: [ 'dev', 'qa', 'prod' ]
    name: Pulumi Preview
    if: github.event_name == 'pull_request'
    needs: check
    uses: ./.github/workflows/pulumi-preview.yaml
    with:
      profile: ${{ matrix.profile }}
    secrets: inherit

  up-non-prod:
    strategy:
      matrix:
        profile: [ 'dev', 'qa' ]
    name: Pulumi Up (Non-Prod)
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    needs: check
    uses: ./.github/workflows/pulumi-up.yaml
    with:
      profile: ${{ matrix.profile }}
    secrets: inherit

  up-prod:
    strategy:
      matrix:
        profile: [ 'prod' ]
    name: Pulumi Up (Prod)
    if: github.ref == 'refs/heads/release/*' && github.event_name == 'workflow_dispatch'
    needs: check
    uses: ./.github/workflows/pulumi-up.yaml
    with:
      profile: ${{ matrix.profile }}
    secrets: inherit
