name: Release

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
      name:
        type: string
        required: true
      version:
        type: string
        required: true
      path:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: semver
        uses: madhead/semver-utils@latest
        with:
          version: ${{ inputs.version }}
          identifier: "rc"
      - name: Get next version
        id: next-version
        run: |
          if [[ "${{ inputs.type }}" == "preminor" ]]; then
            VERSION="${{ steps.semver.outputs.inc-preminor }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Change version
        uses: mikefarah/yq@master
        with:
          cmd: >
            yq -i
            '.version = "${{ steps.next-version.outputs.version }}"'
            ${{ inputs.path }}/app.yaml
      - name: Push commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update app.yaml version of ${{ inputs.name }} to v${{ steps.next-version.outputs.version }}"
          branch: main
